version: 2.1

workflows:
  image-build:
    jobs:
      - build:
          context:
            - github

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/photoprism_ai_tagger:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/photoprism_ai_tagger:$TAG